### ISSUE TITLE
Add cake-contrib user

### ISSUE THREAD

**Issue by gep13** [AlbertoMonteiro/Cake.CoverageComparer#1]
First of all, I wanted to thank you for adding to the Cake community by adding this addin.

I was just wondering if you had seen this blog post:

http://cakebuild.net/blog/2016/08/cake-contribution-organization

We are currently going through a process of increasing the visibility of addins, and also trying to ensure their long term maintainability.

To that end, we are asking addin creators to add the cake-contrib user on NuGet as a co-owner (this can be done through the NuGet website by clicking on Manage Owners on the package page).

Would you be interested in doing this? If you have any questions about this, please let me know. There was some initial concern that the Cake Team were trying to "take over" packages, and that couldn't be further from the truth, and if you have this concern, or others, I would like to address them.

Thanks!

**Comment by AlbertoMonteiro** [comment]
Done @gep13 !
Thanks for the contact, I wasn't expecting that!!
It was an awesome surprise!!

**Comment by gep13** [comment]
>@AlbertoMonteiro said...
It was an awesome surprise!!

I am glad to hear it.  We, the Cake Team, have some automation in place that lets us know when a new package is pushed to NuGet that starts with the `Cake.` convention, and if this turns out to be a Cake Addin, we like to follow up to offer any support that we can.

The reason that we ask that the cake-contrib user is added on NuGet is to allow other folks on the Cake team to push a new package version, should the need arise.  This actually came up recently on a podcast that I did:

https://scot-osum.gitlab.io/podcasts/2020/06/22/sosum-podcast-s01-ep02.html

Would you also be interested in bringing this repository under the Cake-Contrib Organisation on GitHub?  You would still have full access to the repository, and you would still be the maintainer of the project, it would just mean that the code lives in a shared place, should the need arise to help out.

Please let me know if you have any questions.

**Comment by AlbertoMonteiro** [comment]
`Would you also be interested in bringing this repository under the Cake-Contrib Organisation on GitHub?`

Sure, what I have to do?

**Comment by AlbertoMonteiro** [comment]
`Would you also be interested in bringing this repository under the Cake-Contrib Organisation on GitHub?`

Sure @gep13 , what I have to do?

**Comment by gep13** [comment]
@AlbertoMonteiro the process is laid out here:

https://github.com/cake-contrib/Home#how-do-i-as-an-addin-author-transfer-a-repository-to-the-organisation

Only the first step, initially transferring the repository to myself, or another Cake Team member, needs to be done by you, the rest of the steps would be taken care of for you.

**Comment by AlbertoMonteiro** [comment]
@gep13 I will transfer to you

**Comment by gep13** [comment]
@AlbertoMonteiro thank you for doing that!

I have completed the movement of the repository into the Cake-Contrib Organisation.  You should have had a request asking you to join the Cake-Contrib Organisation, and you will have full access to this repository when you join.

Do you have a Twitter account?  If so, what is your username?  Also, what is the best email address to you to invite you to a Slack Team?  These are two mechanisms that we use for keeping in contact with addin maintainers, and to allow you to ask questions if you have any.

**Comment by AlbertoMonteiro** [comment]
@gep13 my twitter is https://twitter.com/AIbertoMonteiro
and my email is 
- alberto.monteiro
- [at]
- live.com

tricky list to avoid bot spam =D

**Comment by gep13** [comment]
@AlbertoMonteiro thanks for the information.  I have followed you from the cake-contrib account on Twitter, and I have sent you an invite to a Slack Team.  Please let me know if you have any questions.
